apiVersion: digitalis.io/v1beta1
kind: DbSecret
metadata:
  name: postgres-creds
  namespace: sergio
  annotations:
    yorkshire: demo
spec:
  vault:
    role: admin
    mount: postgres
  rollout:
    - kind: Deployment
      name: postgres-client
