apiVersion: digitalis.io/v1beta1
kind: DbSecret
metadata:
  name: dbsecret-template
  namespace: sergio
  annotations:
    yorkshire: demo
spec:
  vault:
    role: admin
    mount: mariadb
  template:
    config.ini: |
      username: {{.username}}
      password: {{.password}}
      connection_url: {{.connection_url}}
