apiVersion: digitalis.io/v1beta1
kind: DbSecret
metadata:
  name: mariadb-creds
  namespace: sergio
  annotations:
    yorkshire: demo
spec:
  vault:
    role: admin
    mount: mariadb
  # rollout:
  #   - kind: Deployment
  #     name: mariadb-client
