apiVersion: digitalis.io/v1
kind: ValsSecret
metadata:
  name: sample-vals-secret
  namespace: sergio
spec:
  data:
    location:
      encoding: text
      ref: ref+vault://secret/yorkshire/location
  ttl: 3600
  type: Opaque
